# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ChartDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ChartDemo
	pod 'AFNetworking', '~> 3.1.0'
	pod 'Charts', :git => 'https://github.com/danielgindi/Charts.git', :branch => 'master'
	pod 'RealmSwift', '~> 2.0.2'
post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.0'
      end
    end
  end 

 target 'ChartDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChartDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
